---
ID: f24957f0-b65d-4c3b-ae74-c257ea8b07cd
Parent: 343700fc-4172-4ff9-9008-c3f33d9c30ce
Template: 343700fc-4172-4ff9-9008-c3f33d9c30ce
Path: /sitecore/templates/Spitfire/Domain/Insurance/Page/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {94A8C8E9-690B-4E65-98E7-F95800222767}
    {8FF3D369-A508-4D2F-84A5-9B6C6BF5E537}
- ID: a4879e42-0270-458d-9c19-a20af3c2b765
  # __Presets
  Type: Treelist
  Value: |
    {2A507E75-D068-4618-9F98-5C3A1D6D3A01}
    {1C15E081-9842-4DA2-ACF3-E7ED7D5B0651}
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  # __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 04bf00db-f5fb-41f7-8ab7-22408372a981
      # __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}">
            <r uid="{0AE60D20-91D6-4059-9B83-9F75C4106C04}" ds="{6AEAF30B-4326-4B92-9947-1B7222B5B819}" id="{DE61BFEF-FC07-4749-BF85-5957A3D24E77}" ph="/page-content/col-sidebar_51e00275-058e-4ce8-95b1-1d4a47fce1b3" />
            <r uid="{ACEA5819-86BC-4195-9830-1C0063B3177F}" id="{8355CEF1-BD86-43B4-B995-24EA6828CE4C}" ph="/page-content/col-content_51e00275-058e-4ce8-95b1-1d4a47fce1b3" />
            <r uid="{51E00275-058E-4CE8-95B1-1D4A47FCE1B3}" id="{96A0D722-703F-4958-B87C-5282BC492362}" ph="page-content" />
            <r uid="{57CB4AC2-BC9A-4C46-A11A-5754A7F60451}" ds="{40886C6F-0F4F-4966-97E3-49DE15AD7765}" id="{788976AB-A6B5-4462-93D6-88EC5A53F234}" ph="page-content" />
            <r uid="{1101220C-29B0-412A-9556-031CBBA326ED}" id="{BB45BD7C-CE8E-4FED-B18F-2A1399EC9CCA}" ph="footer" />
            <r uid="{3611D10A-2258-44B8-8CAC-5968562DC884}" id="{5B08C51D-2BAE-4284-BC9A-A3FD12C0F06B}" ph="/header/menu/menu-widgets" />
            <r uid="{10FB564E-67A1-4940-8E52-B2E34461006E}" id="{FD79E80F-A107-42C2-ABC6-AD952D5CA467}" ph="/header/menu/menu-widgets" />
            <r uid="{3FB3232E-CC5C-4E3A-BCDF-AD5F4C96C103}" id="{5ABEAD4D-A364-4205-A11D-54A68DAE9545}" ph="/header/menu/menu-widgets" />
            <r uid="{8EA1083D-1068-4FBA-8E84-718526149785}" id="{A8C0A950-4534-4037-9AD2-999F5FEAEE62}" ph="/header/menu" />
            <r uid="{4AA44ECF-CD05-4AC3-AA6B-EFC0C3C3DAB3}" id="{D9840C19-F04E-4C9F-834E-92EEED5343C7}" ph="header" />
          </d>
        </r>
    - ID: 1b483e91-d8c4-4d19-ba03-462074b55936
      # NavigationTitle
      Value: $name
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150824T175451Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: ca0479ce-0bfe-4522-83de-ba688b380a78
      # BrowserTitle
      Value: $name
