---
ID: 8da8d7f9-ca47-4962-a742-7e8b4293189f
Parent: a19ba474-d04e-41ea-9005-ba36376ee857
Template: a19ba474-d04e-41ea-9005-ba36376ee857
Path: /sitecore/templates/Spitfire/ItemTypes/Author/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151120T102641Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b6ad00ba-c920-44fc-8fb6-96de85376133
      # Author
      Value: $name
