---
ID: 4e160be5-eecd-4090-9461-1cc366d47ae0
Parent: f023e983-3c84-49b8-bdfd-fcddbf568157
Template: f023e983-3c84-49b8-bdfd-fcddbf568157
Path: /sitecore/templates/Spitfire/Domain/Banking/Category/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {4B219152-BD98-4E3F-A625-74F050B5E699}
    {62230B9A-25D2-436F-ADAC-55C2FCBD0448}
    {8BF8EFD4-0E6A-4F11-9C64-C16F79111552}
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  # __Renderings
  Type: layout
  Value: |
    <r>
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}">
        <r uid="{4BF3D46A-D503-4152-A526-77D9F1616424}" id="{BB45BD7C-CE8E-4FED-B18F-2A1399EC9CCA}" ph="footer" />
        <r uid="{9C9DB805-296E-4343-A183-85FE5DD21E6D}" id="{5B08C51D-2BAE-4284-BC9A-A3FD12C0F06B}" ph="/header/menu/menu-widgets" />
        <r uid="{18D56424-F60C-42E5-B571-9EB7CBD6DFC9}" id="{5ABEAD4D-A364-4205-A11D-54A68DAE9545}" ph="/header/menu/menu-widgets" />
        <r uid="{365CFC84-1529-4926-8A23-4D19EF9FE654}" id="{668E785F-7884-43BF-AFE2-1F3830EBE078}" ph="/header/menu" />
        <r uid="{684C5045-E8C6-4B39-9758-BAE1D9A31190}" id="{F240D3CE-B89E-4EF9-980D-DFC6B28BE88C}" ph="header" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 04bf00db-f5fb-41f7-8ab7-22408372a981
      # __Final Renderings
      Type: Layout
      Value: |
        <r>
          <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}">
            <r uid="{1A3037CF-88B6-4895-91A8-438636520EF8}" id="{3B04617D-4E9A-4210-BE56-BB8BB68F2B0F}" ph="page-content" />
            <r uid="{EC459A7A-42BC-4DAA-A1C0-EDECA92B81DD}" id="{64F8F3A6-F8F1-48DA-BE8D-B72CC651F23B}" ph="page-content" />
            <r uid="{4BF3D46A-D503-4152-A526-77D9F1616424}" id="{BB45BD7C-CE8E-4FED-B18F-2A1399EC9CCA}" ph="footer" />
            <r uid="{9C9DB805-296E-4343-A183-85FE5DD21E6D}" id="{5B08C51D-2BAE-4284-BC9A-A3FD12C0F06B}" ph="/header/menu/menu-widgets" />
            <r uid="{18D56424-F60C-42E5-B571-9EB7CBD6DFC9}" id="{5ABEAD4D-A364-4205-A11D-54A68DAE9545}" ph="/header/menu/menu-widgets" />
            <r uid="{365CFC84-1529-4926-8A23-4D19EF9FE654}" id="{668E785F-7884-43BF-AFE2-1F3830EBE078}" ph="/header/menu" />
            <r uid="{684C5045-E8C6-4B39-9758-BAE1D9A31190}" id="{F240D3CE-B89E-4EF9-980D-DFC6B28BE88C}" ph="header" />
          </d>
        </r>
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20160508T172050Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
