---
ID: d5830167-eac2-415e-8c95-250ffc9bf445
Parent: 94a8c8e9-690b-4e65-98e7-f95800222767
Template: 94a8c8e9-690b-4e65-98e7-f95800222767
Path: /sitecore/templates/Habitat/Project/Website/Page Types/Article/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {94A8C8E9-690B-4E65-98E7-F95800222767}
    {8FF3D369-A508-4D2F-84A5-9B6C6BF5E537}
- ID: a4879e42-0270-458d-9c19-a20af3c2b765
  # __Presets
  Type: Treelist
  Value: |
    {2A507E75-D068-4618-9F98-5C3A1D6D3A01}
    {1C15E081-9842-4DA2-ACF3-E7ED7D5B0651}
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  # __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 04bf00db-f5fb-41f7-8ab7-22408372a981
      # __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
          <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{DF9D127F-B388-4746-89E7-7E6D78D35186}">
            <r uid="{5358E404-BBC3-4D11-B68E-276886D2BA7A}" id="{8355CEF1-BD86-43B4-B995-24EA6828CE4C}" ph="/page-content/col-content_086ed505-01d8-490b-8a9d-f68ae14f47d7" />
            <r uid="{63674056-B12D-4121-92D4-2DD81DE61C62}" ds="{14368BAE-D1D4-45BA-BC47-B1189AF83EB5}" id="{87304361-D27E-4D15-8AE6-23B9BE1B1DB4}" ph="/page-content/col-sidebar_086ed505-01d8-490b-8a9d-f68ae14f47d7" />
            <r uid="{FADE63AA-F8D6-4A93-99CE-5D5A45B5129A}" ds="{14368BAE-D1D4-45BA-BC47-B1189AF83EB5}" id="{87304361-D27E-4D15-8AE6-23B9BE1B1DB4}" ph="/page-content/col-sidebar" />
            <r uid="{F8E470A1-2625-4E14-9526-C93043797960}" id="{8355CEF1-BD86-43B4-B995-24EA6828CE4C}" ph="/page-content/col-content" />
            <r uid="{086ED505-01D8-490B-8A9D-F68AE14F47D7}" id="{96A0D722-703F-4958-B87C-5282BC492362}" ph="page-content" />
            <r uid="{BC6BB3D1-9406-4437-A68D-1AACD47B290D}" id="{BB45BD7C-CE8E-4FED-B18F-2A1399EC9CCA}" ph="footer" />
            <r uid="{88543D28-D6C2-4BDE-94DD-C578717E3B79}" id="{5B08C51D-2BAE-4284-BC9A-A3FD12C0F06B}" ph="/header/menu/menu-widgets" />
            <r uid="{4C0ACE67-6EC0-4CB7-8D44-49C17BB28551}" id="{5ABEAD4D-A364-4205-A11D-54A68DAE9545}" ph="/header/menu/menu-widgets" />
            <r uid="{5ACF6261-C2AB-4C08-96C5-5A0B1B254790}" id="{668E785F-7884-43BF-AFE2-1F3830EBE078}" ph="/header/menu" />
            <r uid="{18D91354-91A4-47C9-A8C7-8F8702D3C7E6}" id="{F240D3CE-B89E-4EF9-980D-DFC6B28BE88C}" ph="header" />
          </d>
        </r>
    - ID: 1b483e91-d8c4-4d19-ba03-462074b55936
      # NavigationTitle
      Value: $name
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150824T175451Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: c30a013f-3cc8-4961-9837-1c483277084a
      # Title
      Value: $name
    - ID: ca0479ce-0bfe-4522-83de-ba688b380a78
      # BrowserTitle
      Value: $name
